/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tugas10;

import Tugas10.Kalkulator;                  // mengimpor kelas kalkulator dari package yang sama, kelas ini digunakan setelah login berhasil
import javax.swing.JOptionPane;             // digunakan untuk menampilkan kotak dialog untuk informasi peringatan
import Tugas10.CommonConstants;             // mengimpor kelas CommonConstants untuk koneksi database
import Tugas10.MyJDBC;                      // mengimpor kelas MyJDBC untuk mengakses koneksi database
import javax.swing.*;                       // mengimpor semua kelas dari paket jvax.swing untuk elemen antarmuka pengguna 
import java.awt.*;                          // mengimpor semua kelas dari paket java.awt untuk fungsi antarmuka pengguna
import java.awt.event.ActionEvent;          // mengimpor kelas untuk menangani tindakan seperti klik tombol
import java.awt.event.ActionListener;       // interface yang harus diimplementasikan untuk menangani action event
import java.awt.event.MouseAdapter;         // digunakan untuk menangani event mouse dengan lebih fleksibel
import java.awt.event.MouseEvent;           // kelas untuk menangani event mouse, misalnya klik.
/**
 *
 * @author lala_
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        addRegisterClickListener();     // menambahkan event listener untuk menangani klik pada elemen yang mengarah ke Register.
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        welcomeLB = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        usernameLB = new javax.swing.JLabel();
        usernameTF = new javax.swing.JTextField();
        passwordLB = new javax.swing.JLabel();
        LoginBT = new javax.swing.JButton();
        passwordTF = new javax.swing.JPasswordField();
        RegisterLB = new javax.swing.JLabel();
        showpasswordCB = new javax.swing.JCheckBox();
        pleaseinsertLB = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeLB.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        welcomeLB.setForeground(new java.awt.Color(204, 153, 0));
        welcomeLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLB.setText("WELCOME!");
        jPanel1.add(welcomeLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, 40));

        jPanel2.setBackground(new java.awt.Color(204, 153, 0));
        jPanel2.setForeground(new java.awt.Color(255, 153, 0));

        usernameLB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        usernameLB.setForeground(new java.awt.Color(153, 51, 0));
        usernameLB.setText("Username");

        usernameTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        passwordLB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        passwordLB.setForeground(new java.awt.Color(153, 51, 0));
        passwordLB.setText("Password");

        LoginBT.setBackground(new java.awt.Color(153, 51, 0));
        LoginBT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoginBT.setForeground(new java.awt.Color(204, 153, 0));
        LoginBT.setText("Login");
        LoginBT.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 153, 0)));
        LoginBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBTActionPerformed(evt);
            }
        });

        passwordTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        RegisterLB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RegisterLB.setForeground(new java.awt.Color(153, 51, 0));
        RegisterLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegisterLB.setText("not a user? register here");

        showpasswordCB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        showpasswordCB.setForeground(new java.awt.Color(153, 51, 0));
        showpasswordCB.setText("show Password");
        showpasswordCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpasswordCBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RegisterLB, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginBT, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLB, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLB, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showpasswordCB))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(usernameLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(showpasswordCB)
                .addGap(18, 18, 18)
                .addComponent(LoginBT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(RegisterLB)
                .addGap(22, 22, 22))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 370, 360));

        pleaseinsertLB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pleaseinsertLB.setForeground(new java.awt.Color(204, 153, 0));
        pleaseinsertLB.setText("Please insert your Username and Password ");
        jPanel1.add(pleaseinsertLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 320, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addRegisterClickListener(){
        // menambahkan event listener pada RgisterLB untuk menangani klik mouse.
        RegisterLB.addMouseListener(new MouseAdapter(){
            // method ini dipanggil saat mouse di klik pada RegisterLB
            public void mouseClicked(MouseEvent e){
                // menutup (dispose) jendela login saat ini.
                Login.this.dispose();
                
                // membuat instance baru dari from Register dan menampilkannya 
                new Register().setVisible(true);
            }
        });
    }
    
    private void LoginBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBTActionPerformed
        // TODO add your handling code here:
        // mengambil input teks dari field usernameTF sebagai username
        String username = usernameTF.getText();
        
        // mengambil input teks dari field passwordTF sebagai password dan mengonversinya ke String
        String password = new String(passwordTF.getPassword());
        
        // memeriksa apakah username dan password valid menggunakan 'validasiLogin' dari kelas MyJDBC
        if(MyJDBC.validasiLogin(username, password)){
            // menampilkan pesan dialog bahwa login berhasil
            JOptionPane.showMessageDialog(Login.this, "Login Successful!");
           
            // menutup jendela login setelah login berhasil
            this.dispose();
            
            // membuka jendela kalkulator sebagai langkah berikutnya setelah login berhasil
            new Kalkulator().setVisible(true);
            
            
        } else {
            // menampilkan pesan dialog bahwa login gagal
            JOptionPane.showMessageDialog(Login.this, "Login Failed");
        }
    }//GEN-LAST:event_LoginBTActionPerformed

    private void showpasswordCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpasswordCBActionPerformed
        // TODO add your handling code here:
        if(showpasswordCB.isSelected()){
            passwordTF.setEchoChar((char)0);
        }else{
           passwordTF.setEchoChar('*');
    }//GEN-LAST:event_showpasswordCBActionPerformed
    }      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginBT;
    private javax.swing.JLabel RegisterLB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JLabel passwordLB;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JLabel pleaseinsertLB;
    private javax.swing.JCheckBox showpasswordCB;
    private javax.swing.JLabel usernameLB;
    private javax.swing.JTextField usernameTF;
    private javax.swing.JLabel welcomeLB;
    // End of variables declaration//GEN-END:variables
}
