/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tugas10;
import Tugas10.CommonConstants;             // mengimpor kelas CommonConstants untuk koneksi database
import Tugas10.MyJDBC;                      // mengimpor kelas MyJDBC untuk mengakses koneksi database
import javax.swing.*;                       // mengimpor semua kelas dari paket jvax.swing untuk elemen antarmuka pengguna 
import java.awt.*;                          // mengimpor semua kelas dari paket java.awt untuk fungsi antarmuka pengguna
import java.awt.event.ActionEvent;          // mengimpor kelas untuk menangani tindakan seperti klik tombol
import java.awt.event.ActionListener;       // interface yang harus diimplementasikan untuk menangani action event
import java.awt.event.MouseAdapter;         // digunakan untuk menangani event mouse dengan lebih fleksibel
import java.awt.event.MouseEvent;           // kelas untuk menangani event mouse, misalnya klik.

/**
 *
 * @author lala_
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Register() {
        initComponents();
        addloginClickListener();    // menambahkan event listener untuk menangani klik pada elemen yang mengarah ke Login
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        HelloLB = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        usernameLB = new javax.swing.JLabel();
        usernameTF = new javax.swing.JTextField();
        passwordLB = new javax.swing.JLabel();
        passwordTF = new javax.swing.JPasswordField();
        RegisterBT = new javax.swing.JButton();
        confirmpassLB = new javax.swing.JLabel();
        confirmpasswordTF = new javax.swing.JPasswordField();
        loginLB = new javax.swing.JLabel();
        showpasswordCB = new javax.swing.JCheckBox();
        PleaseinsertLB = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 153, 0));
        jLabel5.setText("Please insert your Username and Password ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(440, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(440, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HelloLB.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        HelloLB.setForeground(new java.awt.Color(204, 153, 0));
        HelloLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HelloLB.setText("HELLO!");
        jPanel1.add(HelloLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, 40));

        jPanel2.setBackground(new java.awt.Color(204, 153, 0));
        jPanel2.setForeground(new java.awt.Color(255, 153, 0));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setPreferredSize(new java.awt.Dimension(370, 360));

        usernameLB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        usernameLB.setForeground(new java.awt.Color(153, 51, 0));
        usernameLB.setText("Username");

        usernameTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        usernameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTFActionPerformed(evt);
            }
        });

        passwordLB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        passwordLB.setForeground(new java.awt.Color(153, 51, 0));
        passwordLB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        passwordLB.setText("Password");

        passwordTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        passwordTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTFActionPerformed(evt);
            }
        });

        RegisterBT.setBackground(new java.awt.Color(153, 51, 0));
        RegisterBT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RegisterBT.setForeground(new java.awt.Color(204, 153, 0));
        RegisterBT.setText("Register");
        RegisterBT.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 153, 0)));
        RegisterBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBTActionPerformed(evt);
            }
        });

        confirmpassLB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        confirmpassLB.setForeground(new java.awt.Color(153, 51, 0));
        confirmpassLB.setText("Confirm Password");

        confirmpasswordTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        confirmpasswordTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmpasswordTFActionPerformed(evt);
            }
        });

        loginLB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginLB.setForeground(new java.awt.Color(153, 51, 0));
        loginLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLB.setText("Have an account? Login Here!");

        showpasswordCB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        showpasswordCB.setForeground(new java.awt.Color(153, 51, 0));
        showpasswordCB.setText("Show Password");
        showpasswordCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpasswordCBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegisterBT, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmpasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordLB, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameLB, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmpassLB, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showpasswordCB)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(loginLB, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(usernameLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmpassLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmpasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showpasswordCB, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(RegisterBT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginLB)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 370, 380));

        PleaseinsertLB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PleaseinsertLB.setForeground(new java.awt.Color(204, 153, 0));
        PleaseinsertLB.setText("Please insert your data:");
        jPanel1.add(PleaseinsertLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTFActionPerformed
        
    }//GEN-LAST:event_usernameTFActionPerformed

    private void passwordTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTFActionPerformed

    }//GEN-LAST:event_passwordTFActionPerformed

    private void confirmpasswordTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmpasswordTFActionPerformed
 
    }//GEN-LAST:event_confirmpasswordTFActionPerformed

    private void RegisterBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBTActionPerformed
        // mengambil input teks dari field usernameTF sebagai username
        String username = usernameTF.getText();
        
        // mengambil input teks dari field passwordTF sebagai password dan mengonversinya ke String
        String password = new String(passwordTF.getPassword());
        
        // mengambil input teks dari field confirmPass dan mengonversinya ke String
        String confirmPass = new String(confirmpasswordTF.getPassword());
        
       // memeriksa apakah panjang username kurang dari 6 karakter 
       if (username.length() < 6){
           // menampilkan pesan dialgo bahwa username harus minimal 6 karakter.
           JOptionPane.showMessageDialog(Register.this, "Username harus terdiri dari minimal 6 karakter. Silahkan coba lagi.");
           return;  // menghentikan eksekusi metode jika validasi gagal
       }
       
       // memeriksa apakah password dan confirmPass tidak cocok
       if (!password.equals(confirmPass)){
           // menampilkan pesan dialago bahwa password tidak cocok
           JOptionPane.showMessageDialog(Register.this, "Password tidak cocok. Silahkan coba lagi.");
           return;  // menghentikan eksekusi metode jika validasi gagal
       }
       
       // memanggil metode Register di MyJDBC untuk mendaftarkan pengguna baru
       if (MyJDBC.register(username, password)){
           // menutup jendela Register jika pendaftaran berhasil
           Register.this.dispose();
           // membuka jendela login setelah pendaftaran berhasil
           Login login = new Login();
           login.setVisible(true);
           // menampilkan pesan dialog bahwa pendaftaran berhasil
           JOptionPane.showMessageDialog(login, "Akun Anda berhasil didaftarkan!");
       } else {
           // menampilkan pesan bahwa username sudah digunakan
            JOptionPane.showMessageDialog(Register.this, "Usernamae Sudah digunakan. Silahkan coba lagi.");
       }
    }//GEN-LAST:event_RegisterBTActionPerformed

    private void showpasswordCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpasswordCBActionPerformed
        // memriksa apakah checkbox showpasswordCB dipilih.  
        if(showpasswordCB.isSelected()){
            // jika iya sistem akan menampilkan password dalam teks biasa dengan mengatur karakter echo ke (char)0
            confirmpasswordTF.setEchoChar((char)0);
            passwordTF.setEchoChar((char)0);
        }else{
           // menyembunyikan password dengan mengatur karakter echo menjadi '*'
           confirmpasswordTF.setEchoChar('*');
           passwordTF.setEchoChar('*'); 
        }
    }//GEN-LAST:event_showpasswordCBActionPerformed
    
     private void addloginClickListener(){
        // menambahkan event listener pada LoginLB untuk menangani event klik mouse.
        loginLB.addMouseListener(new MouseAdapter(){
            // method ini dipanggil saat mouse diklik pada LoginLB
            public void mouseClicked(MouseEvent e){
                // menutup (dispose) jendela Register 
                Register.this.dispose();
                
                // membuat instance baru dari from login dan menampilkannya
                new Login().setVisible(true);
            }
        });
    }
    
    private boolean validasiUserInput(String username, String password, String confirmPass){
        // memeriksa apakah salah satu input (username, password, atau confirmPass) kosong
        if(username.length() == 0 || password.length() == 0 || confirmPass.length() == 0) return false;
        // memeriksa apakah panjang username kurang dari 6 karakter
        if(username.length() < 6) return false;
        // memeriksa apakah password dan confirmPass tidak cocok
        if(!password.equals(confirmPass)) return false;
        
        // mengembalikan true jika semua validasi input berhasil
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HelloLB;
    private javax.swing.JLabel PleaseinsertLB;
    private javax.swing.JButton RegisterBT;
    private javax.swing.JLabel confirmpassLB;
    private javax.swing.JPasswordField confirmpasswordTF;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JLabel loginLB;
    private javax.swing.JLabel passwordLB;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JCheckBox showpasswordCB;
    private javax.swing.JLabel usernameLB;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
